In [1]:
import pandas as pd 
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn import datasets
from sklearn.model_selection import cross_val_score,cross_val_predict
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score

df=pd.read_csv(r"C:\Users\sgoff\Downloads\student_extended_ml_dataset2.csv")

In [2]:
df

Name  Age  Gender  Hours_Studied   IQ  Physics_Marks  \
0            Jason Vargas   19    Male       8.140821   92             87   
1          Sandra Wiggins   35  Female       9.825626  112             86   
2             Julia Olsen   33    Male       8.835372  131             87   
3       Robert Pennington   33    Male       2.482483  138             70   
4           Kayla Sellers   28  Female       4.419793   90             95   
...                   ...  ...     ...            ...  ...            ...   
4995         Steven Lynch   30  Female       3.653474  143             93   
4996       Donna Hamilton   33  Female       1.096493  132             68   
4997   Mrs. Ashley Howard   38    Male       4.156770  111             76   
4998        Kendra Murray   18  Female       6.788548  137             81   
4999  Christine Rodriguez   38    Male       1.627111   95             52   

      Math_Marks  Chemistry_Marks  Has_Part_Time_Job Study_Hours_Group  
0             43               85               True              High  
1             81               54              False              High  
2             52               57               True              High  
3             86               83              False               Low  
4             48               83               True               Low  
...          ...              ...                ...               ...  
4995          59               85               True               Low  
4996          70               99               True               Low  
4997          96               71              False               Low  
4998          98               73              False              High  
4999          70               74               True               Low  

[5000 rows x 10 columns]

In [3]:
df['Gender'] = df['Gender'].map({'Male': 0, 'Female': 1})


In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Has_Part_Time_Job'] = le.fit_transform(df['Has_Part_Time_Job'])

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Study_Hours_Group'] = le.fit_transform(df['Study_Hours_Group'])

In [6]:
df

Name  Age  Gender  Hours_Studied   IQ  Physics_Marks  \
0            Jason Vargas   19       0       8.140821   92             87   
1          Sandra Wiggins   35       1       9.825626  112             86   
2             Julia Olsen   33       0       8.835372  131             87   
3       Robert Pennington   33       0       2.482483  138             70   
4           Kayla Sellers   28       1       4.419793   90             95   
...                   ...  ...     ...            ...  ...            ...   
4995         Steven Lynch   30       1       3.653474  143             93   
4996       Donna Hamilton   33       1       1.096493  132             68   
4997   Mrs. Ashley Howard   38       0       4.156770  111             76   
4998        Kendra Murray   18       1       6.788548  137             81   
4999  Christine Rodriguez   38       0       1.627111   95             52   

      Math_Marks  Chemistry_Marks  Has_Part_Time_Job  Study_Hours_Group  
0             43               85                  1                  0  
1             81               54                  0                  0  
2             52               57                  1                  0  
3             86               83                  0                  1  
4             48               83                  1                  1  
...          ...              ...                ...                ...  
4995          59               85                  1                  1  
4996          70               99                  1                  1  
4997          96               71                  0                  1  
4998          98               73                  0                  0  
4999          70               74                  1                  1  

[5000 rows x 10 columns]

In [7]:
df=df.drop('Name',axis=1)

In [8]:
df

Age  Gender  Hours_Studied   IQ  Physics_Marks  Math_Marks  \
0      19       0       8.140821   92             87          43   
1      35       1       9.825626  112             86          81   
2      33       0       8.835372  131             87          52   
3      33       0       2.482483  138             70          86   
4      28       1       4.419793   90             95          48   
...   ...     ...            ...  ...            ...         ...   
4995   30       1       3.653474  143             93          59   
4996   33       1       1.096493  132             68          70   
4997   38       0       4.156770  111             76          96   
4998   18       1       6.788548  137             81          98   
4999   38       0       1.627111   95             52          70   

      Chemistry_Marks  Has_Part_Time_Job  Study_Hours_Group  
0                  85                  1                  0  
1                  54                  0                  0  
2                  57                  1                  0  
3                  83                  0                  1  
4                  83                  1                  1  
...               ...                ...                ...  
4995               85                  1                  1  
4996               99                  1                  1  
4997               71                  0                  1  
4998               73                  0                  0  
4999               74                  1                  1  

[5000 rows x 9 columns]

In [9]:
df.columns

Index(['Age', 'Gender', 'Hours_Studied', 'IQ', 'Physics_Marks', 'Math_Marks',
       'Chemistry_Marks', 'Has_Part_Time_Job', 'Study_Hours_Group'],
      dtype='object')

In [22]:
!pip install pandas_summary 
from pandas_summary import DataFrameSummary
dfs=DataFrameSummary(df)
dfs.columns_stats

Age Gender Hours_Studied       IQ Physics_Marks Math_Marks  \
counts           5000   5000          5000     5000          5000       5000   
uniques            28      2          5000       71            61         61   
missing             0      0             0        0             0          0   
missing_perc       0%     0%            0%       0%            0%         0%   
types         numeric   bool       numeric  numeric       numeric    numeric   

             Chemistry_Marks Has_Part_Time_Job Study_Hours_Group  
counts                  5000              5000              5000  
uniques                   61                 2                 2  
missing                    0                 0                 0  
missing_perc              0%                0%                0%  
types                numeric              bool              bool

In [10]:
Features=df[['Age', 'Gender', 'Hours_Studied', 'IQ', 'Physics_Marks', 'Math_Marks',
       'Chemistry_Marks', 'Has_Part_Time_Job']]
Target=df[['Study_Hours_Group']]

In [11]:
import numpy as np
X=np.array(Features)
Y=np.array(Target).ravel()


In [12]:
from sklearn import preprocessing
X=preprocessing.MinMaxScaler().fit_transform(X)

In [21]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
model_1=knn.fit(X,Y)
model_1.score(X,Y)

0.9648

In [18]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

classifier = KNeighborsClassifier()
cross_valid_scores=[]
for k in range(1,100):
    Knn = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(Knn,X,Y,cv=10,scoring='accuracy')
    cross_valid_scores.append(scores.mean())
print("optimal k with cross validation: ",np.argmax(cross_valid_scores))

optimal k with cross validation:  92


In [20]:
from sklearn.model_selection import cross_val_score
classifier = KNeighborsClassifier(n_neighbors=92)
scores=cross_val_score(classifier,X,Y,cv=10)
print(scores.mean())
Y_predd=cross_val_predict(classifier,X,Y,cv=10)
print(confusion_matrix(Target,Y_predd))

0.9655999999999999
[[2706   57]
 [ 115 2122]]


In [14]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=10)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=10000)
model.fit(X_train,Y_train)
y_pred = model.predict(X_test)

print("The accuracy of the model is : ",model.score(X_test,Y_test))
print(confusion_matrix(Y_test,y_pred))

The accuracy of the model is :  0.998
[[558   1]
 [  1 440]]


In [15]:
param_grid={'C':[0.1,1,5,10,20,30,40,50,60,70,100,200]}

In [16]:
model = LogisticRegression(max_iter=10000)
grid=GridSearchCV(model,param_grid,refit=True)
grid.fit(X,Y)
print(grid.best_estimator_)
predicted=cross_val_score(grid.best_estimator_,X,Y,cv=4)
print(predicted.mean())
Y_predd=cross_val_predict(grid.best_estimator_,X,Y,cv=4)
print(confusion_matrix(Target,Y_predd))

LogisticRegression(C=200, max_iter=10000)
0.9994000000000001
[[2761    2]
 [   1 2236]]


SyntaxError: invalid syntax (1288053226.py, line 1)